comments: 
    provider: duoshuo
    duoshuo:
        short_name: intohole
title: 布衣客
safe: false
markdown: kramdown
highlighter: pygments
redirects: yes
site_domain: http://www.buyiker.com
author: IntoHole
#monokai manni rrt perldoc borland colorful default murphy vs trac fruity native
code_type: manni
#index.html 每个ｔａｇ展现的链接数目
page_limit: 10
#设置变量时候，不要ｔａｂ，一定要空格
indexs:
 - site: 首页
   url: index.html
 - site: 博客标签 
   url: tagcloud.html
 - site: 我 
   url: my.html
   tag: my
   weight: 17
 - site: 开源 
   url: open.html
   tag: open
 - site: 深度学习
   url: dl.html
   tag: dl
 - site: 机器学习
   url: ml.html
   tag: ml
 - site: 自然语言
   url: nlp.html
   tag: nlp
 - site: 爬虫 
   url: spider.html
   tag: spider 
 - site: 编程
   url: tech.html
   tag: tech
 - site: 开发语言
   url: language.html
   tag: lan
 - site: 前端开发   
   url: frontend.html
   tag: web 
 - site: 生活
   url: life.html
   tag: life
 - site: 论文
   url: paper.html
   tag: paper
 - site: 关于me
   url: resume.html
 
 
page_404:
  refresh_time: 7
  btns:
     - info: 看看我的Github
       url: https://github.com/intohole
     - info: 看看首页
       url: /index.html

resume:
 Desc:
   - info: "机器学习 自然语言处理 架构 前端  全栈工程师 为解决问题而努力，没有高大上的词汇，只有最平凡的词汇，用程序延伸自己的思想 etc ... "

# type : http://www.fontawesome.com.cn/ 请参考这个网站图标，一般来说，不需要fa开头，就是方便集成而已
 Jobs:
   -
     type: envelope
     name: aihai2800@126.com
     url: mailto:aihai2800@126.com
   - 
     type: github 
     name: intohole
     url: https://github.com/intohole
   - 
     type: weibo
     name: 看似大男人的小男人
     url: http://weibo.com/1152049780 
   - 
     type: battery-full
     name: 工作经历
     url: /2015/05/05/resume.html
